# Generated by Django 5.2.6 on 2025-09-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_classroom_strength_alter_classroom_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassRoom',
            new_name='ClassModel',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classroom',
            new_name='student_class',
        ),
        migrations.AlterModelTable(
            name='classmodel',
            table='class',
        ),
    ]
