# Generated by Django 5.2.6 on 2025-09-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_email_remove_student_student_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
    ]
