# Generated by Django 5.2.6 on 2025-09-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='students.classmodel'),
        ),
    ]
