# Generated by Django 5.2.6 on 2025-10-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
