# Generated by Django 5.2.6 on 2025-10-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('App Development', 'App Development'), ('Meetings', 'Meetings')], default='General', max_length=50),
        ),
    ]
